### ISSUE TITLE
تشخیص برنامه به عنوان ویروس

### ISSUE THREAD

**Issue by MansourM** [AblRadmanesh/Android#1]
با سلام
خدا قوت، این داشتان واقعا دغدغه ی برنامه نویساس
فقط ویندوز برنامه تغییر dns شما رو به عنوان ویروس شناسایی و حذف میکنه.
من بچ اسکریپت حرفه ای نیستم ولی یه اسکریپ واسه این کار نوشتم، اونم میتونید اضافه کنید:
https://github.com/MansourM/ez-dns-changer.bat

**Comment by AblRadmanesh** [comment]
> با سلام
> خدا قوت، این داشتان واقعا دغدغه ی برنامه نویساس
> فقط ویندوز برنامه تغییر dns شما رو به عنوان ویروس شناسایی و حذف میکنه.
> من بچ اسکریپت حرفه ای نیستم ولی یه اسکریپ واسه این کار نوشتم، اونم میتونید اضافه کنید:
> https://github.com/MansourM/ez-dns-changer.bat

سلام ممنون بابت نظرتون، خدمتتون عارضم اتفاقا همین مورد هم بچ اسکریپته اما از اونجایی که اجرای این دستورات نیازمند دسترسی ادمین هست گفتیم برنامه بشه که خودکار دسترسی را بگیره، نکته دیگه اینکه کار کردن باهاش هم راحت تر بشه خیلی از دوستان شاید بعدا فایل رو گم کنن اما وقتی به شکل برنامه باشه دسترسی راحت تره براشون 
دلیل این نوع تشخیص آنتی ویروس هم ناشناخته بودنه فایله به همین جهت سعی میکنم با توجه به این مورد فایل. bat رو هم قرار بدم
https://github.com/AblRadmanesh/DNSchanger

**Comment by MansourM** [comment]
چند خط اول اسکریپت منو ببینید یه ترفندی هست که برنامه خودکار دسترسی ادمین میده، میتونید از این روش استفاده کنید
